name 'apache'
maintainer 'Victor'
maintainer_email 'vtic22@gmail.com'
license 'all_rights'
description 'Installs/Configures server apache'
long_description 'Installs/Configures server apache'
version '0.1.0'
